version: "3.8"
services:
  strapi:
    container_name: strapi
    build: ./chess_db
    image: mystrapi:latest
    restart: unless-stopped
    env_file: ./chess_db/.env
    volumes:
      - ./chess_db/config:/opt/app/config
      - ./chess_db/src:/opt/app/src
      - ./chess_db/package.json:/opt/app/package.json
      - ./chess_db/yarn.lock:/opt/yarn.lock
      - ./chess_db/.env:/opt/app/.env
      - ./chess_db/.tmp:/opt/app/.tmp
    ports:
      - "1337:1337"
    networks:
      - strapi_network

  fastapi:
    container_name: fastapi
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
    networks:
      - strapi_network

networks:
  strapi_network:
